Models/Employee.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Telintec_RH.Models
{
    [Table("Employee", Schema = "TIRH")]
    public class Employee
    {
        [Key]
        [Display(Name = "ID")]
        public int? ID { get; set; }

        [Required]
        [Display(Name = "full_name")]
        [Column(TypeName = "varchar(100)")]
        public string fulleName { get; set; } = string.Empty;

        [Required]
        [Display(Name = "CIN")]
        [Column(TypeName = "varchar(250)")]
        public string cin { get; set; } = string.Empty;

        [Display(Name = "Image")]
        [Column(TypeName = "varchar(250)")]
        public string? image { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Tel")]
        [Column(TypeName = "varchar(100)")]
        public string Tel { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Statu")]
        [Column(TypeName = "varchar(250)")]
        public string statu { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Salary")]
        public double salary { get; set; }

        [Required]
        [Display(Name = "Poste")]
        [Column(TypeName = "varchar(100)")]
        public string poste { get; set; } = string.Empty;

        public int DepartementID { get; set; }
        [ForeignKey("DepartementID")]
        public Departement? Departement { get; set; }
    }
}

Controllers/DepartementController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using Telintec_RH.Data;
using Telintec_RH.Models;

namespace Telintec_RH.Controllers
{
    public class DepartementController : Controller
    {
        private readonly AppDbContext _context;

        public DepartementController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int pg = 1, string text = "")
        {

            if (HttpContext.Session.GetString("userAuthenticated") == "true")
            {
                List<Departement> departements;
                if (text != "" && text != null)
                {
                    departements = _context.Departements.Where(p => p.nom.Contains(text)).ToList();

                }
                else
                {
                    departements = _context.Departements.ToList();

                }
                const int pageSize = 6; 
                if (pg < 1) pg = 1;
                int recsCount = departements.Count();
                var pager = new Pager(recsCount, pg, pageSize);
                this.ViewBag.Pager = pager;
                int recSkip = (pg - 1) * pageSize;
                var data = departements.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                return View(data);

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

     public IActionResult Create()
        {
            if((HttpContext.Session.GetString("userAuthenticated") == "true"))
                {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Departement model)
        {
            if (ModelState.IsValid)
            {
                _context.Departements.Add(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

     public IActionResult Update(int? id)
        {

            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                var data = _context.Departements.Find(id);
                if (data != null)
                {
                    return View(data);
                }
                else
                {
                    return RedirectToAction(nameof(Index));
                }
                
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Departement model)
        {
           
            if (ModelState.IsValid)
            {
                _context.Departements.Update(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            var dep = _context.Departements.Find(id);
            if (dep != null)
            {
                _context.Departements.Remove(dep);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));


        }




    }
}

Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Telintec_RH.Data;
using Telintec_RH.Models;

namespace Telintec_RH.Controllers
{
    public class EmployeeController : Controller
    {

        private readonly AppDbContext _context;

        public EmployeeController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int pg = 1, string text = "")
        {

            if (HttpContext.Session.GetString("userAuthenticated") == "true")
            {
                List<Employee> employees;
                if (text != "" && text != null)
                {

                    employees = _context.Employees.Where(p => p.fulleName.Contains(text)).Include(x => x.Departement).ToList();

                }
                else
                {
                    employees = _context.Employees.ToList();

                }
                const int pageSize = 6;
                if (pg < 1) pg = 1;
                int recsCount = employees.Count();
                var pager = new Pager(recsCount, pg, pageSize);
                this.ViewBag.Pager = pager;
                int recSkip = (pg - 1) * pageSize;
                var data = employees.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                ViewBag.Departments = _context.Departements.OrderBy(x => x.nom).ToList();
                return View(data);

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public IActionResult Create()
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                ViewBag.Departments = _context.Departements.OrderBy(x => x.nom).ToList();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public IActionResult Update(int? id)
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                var data = _context.Employees.Find(id);
                ViewBag.Departments = _context.Departements.OrderBy(x => x.nom).ToList();
                return View(data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Employee model)
        {
            UploadImage(model);

            if (ModelState.IsValid)
            {
                _context.Employees.Add(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Employee model)
        {
            UploadImage(model);
            if (ModelState.IsValid)
            {
                _context.Employees.Update(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            var emp = _context.Employees.Find(id);
            if (emp != null)
            {
                _context.Employees.Remove(emp);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));


        }


        private void UploadImage(Employee model)
        {
            var file = HttpContext.Request.Form.Files;
            var x = model.image;
            if (file.Count() > 0)
            {
                string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(file[0].FileName);
                var fileStream = new FileStream(Path.Combine(@"wwwroot/", "Images", ImageName), FileMode.Create);
                file[0].CopyTo(fileStream);
                model.image = ImageName;
                Console.Write(model.image);
            }
            else if (model.image == null && model.ID == null)
            {
                model.image = "Default.png";
            }
            else
            {
                model.image = x;
            }
        }

    }
}

Views/Employee/Create.cshtml
@model Telintec_RH.Models.Employee

@{
    ViewData["Title"] = "Create-Employee";
}

<h1>Create</h1>

<h4>New Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" readonly/>
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fulleName" class="control-label"></label>
                <input asp-for="fulleName" class="form-control" />
                <span asp-validation-for="fulleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cin" class="control-label"></label>
                <input asp-for="cin" class="form-control" />
                <span asp-validation-for="cin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input type="file" asp-for="image" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="statu" class="control-label"></label>
                <select asp-for="statu" class="form-control">
                    <option value="WORKING">WORKING</option>
                    <option value="ABSENT">ABSENT</option>
                    <option value="HOLIDAY">HOLIDAY</option>
                </select>
                <span asp-validation-for="statu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="salary" class="control-label"></label>
                <input asp-for="salary" class="form-control" />
                <span asp-validation-for="salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="poste" class="control-label"></label>
                <input asp-for="poste" class="form-control" />
                <span asp-validation-for="poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartementID" class="control-label">Department</label>
                <select asp-for="DepartementID" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Departments,"ID","nom" ))">
                    <option value="">Chose Department...</option>
                </select>
                <span asp-validation-for="DepartementID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" style="background-color: #2A36B8 !important; color:white !important ; margin-top:10px !important; width:90px !important" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index" style="color:  #000C8E !important; text-decoration: none !important; font-size:16px !important; font-weight:600 !important; margin-top:10px !important;">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Employee/Index.cshtml
@model IEnumerable<Telintec_RH.Models.Employee>

@{
    ViewData["Title"] = "Employees";

    int cmpt = 0;
    double ts = 0;
    foreach (var item in Model)
    {
        cmpt += 1;
        ts += item.salary;
    }
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}
<div style="display:flex; width:100%;">
<div class="analytics">
        <div class="card">
            <h6>Total Employees</h6>
            <div class="card-head">
                <h4>@cmpt</h4>
            </div>
        </div>
</div>
    <div class="analytics">
        <div class="card">
            <h6>Total Salaries</h6>
            <div class="card-head">
                <h4>@ts</h4>
            </div>
            <h6>DH</h6>
        </div>
    </div>


</div>

<div style="display: flex !important; width:100%">
    <form asp-controller="Departement" asp-action="Index" style="width:70%">
        <input type="text" name="text" placeholder="Search" style="color:gray ; width:80%; border-radius:7px; padding:7px; color:#000C8E " />
        <button type="submit" style="margin-left:5px; background-color:#000C8E; border-width:1px; border-color:#000C8E; padding:8px; border-radius:5px; height:40px; width:40px; margin-top:26px;">
            <i class="fa-solid fa-magnifying-glass" style="color:white"></i>

        </button>
    </form>
    <a style="text-decoration:none; background-color:#000C8E; color:white; border-width:1px; border-color:#000C8E;
       border-radius:7px; height:40px; width:9%; padding:8px; margin-left:285px; margin-top:29px" asp-action="Create">
        <i class="fa-solid fa-people-group" style="margin-right:5px;"></i>

        <span>Add Emp</span>
    </a>

</div>

<div style="margin-top:30px; margin-bottom:0px; width:100%; height:35px; border-top-left-radius:9px;border-top-right-radius:9px;
     background-color:#000C8E; padding:6px">
    <p style="color:white; font-size:14px; font-weight:600; margin-left:20px">Employees Management</p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fulleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.statu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.poste)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Departement.nom)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    <b>#@Html.DisplayFor(modelItem => item.ID)</b>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fulleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cin)
            </td>
            <td>
                <img src="~/Images/@item.image" height="42px" width="42px" style="border-radius:15px !important;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.statu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.poste)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Departement.nom)
            </td>
            <td>
                    <a asp-controller="Employee" asp-action="Update" asp-route-id="@item.ID" style="width: 32px;height: 32px; text-decoration:none; color:#2A36B8">
                        <i class="fa-regular fa-pen-to-square"></i>
                    </a> |
                    <a onclick="return confirm('Are you sure of deleting...?')" asp-controller="Employee" asp-action="Delete" asp-route-id="@item.ID" style="text-decoration:none;margin-left:5px;width: 32px;height: 32px;color:#2A36B8">
                        <i class="fa-solid fa-trash-can"></i>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

<div class="pagination">
    @if (pager.TotalPages > 0)
    {
        <ul style="margin-top:45px !important">
            @if (pager.CurrentPage > 1)
            {
                <li style="display:inline">
                    <a class="prev-btn" asp-controller="Employee" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">&lt;before</a>
                </li>

            }
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="@(pge == pager.CurrentPage ? "active" : "page-item") " style="display:inline">
                    <a class="page-number" asp-controller="Employee" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }
            <li style="display:inline">
                <a asp-controller="Employee" asp-action="Index" asp-route-pg="@(pager.TotalPages)" class="prev-btn">next &gt; </a>
            </li>
        </ul>
    }

</div>

Views/Employee/Update.cshtml
@model Telintec_RH.Models.Employee

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>This Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" readonly />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fulleName" class="control-label"></label>
                <input asp-for="fulleName" class="form-control" />
                <span asp-validation-for="fulleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="cin" class="control-label"></label>
                <input asp-for="cin" class="form-control" />
                <span asp-validation-for="cin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="image" class="control-label"></label>
                <input type="file" asp-for="image" class="form-control" />
                <span asp-validation-for="image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tel" class="control-label"></label>
                <input asp-for="Tel" class="form-control" />
                <span asp-validation-for="Tel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="statu" class="control-label"></label>
                <select asp-for="statu" class="form-control">
                    <option value="WORKING">WORKING</option>
                    <option value="ABSENT">ABSENT</option>
                    <option value="HOLIDAY">HOLIDAY</option>
                </select>
                <span asp-validation-for="statu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="salary" class="control-label"></label>
                <input asp-for="salary" class="form-control" />
                <span asp-validation-for="salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="poste" class="control-label"></label>
                <input asp-for="poste" class="form-control" />
                <span asp-validation-for="poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartementID" class="control-label">Propriétaire</label>
                <select asp-for="DepartementID" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Departments,"ID","nom" ))">
                    <option value="">Chose Department...</option>
                </select>
                <span asp-validation-for="DepartementID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" style="background-color: #2A36B8 !important; color:white !important ; margin-top:10px !important; width:90px !important" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index" style="color:  #000C8E !important; text-decoration: none !important; font-size:16px !important; font-weight:600 !important; margin-top:10px !important;">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}