Models/Operation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Telintec_RH.Models
{
    [Table("Operation", Schema = "TIRH")]
    public class Operation
    {
        [Key]
        [Display(Name = "ID")]
        public int? ID { get; set; }

        [Display(Name = "Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMMM-yyyy}")]
        public DateTime Date { get; set; }

        [Display(Name = "Contrat")]
        [Column(TypeName = "varchar(250)")]
        public string? contrat { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Montant")]
        public double montant { get; set; }

        public int EmployeeID { get; set; }
        [ForeignKey("EmployeeID")]
        public Employee? Employee { get; set; }
    }
}

Controllers/AbsenceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Telintec_RH.Data;
using Telintec_RH.Models;

namespace Telintec_RH.Controllers
{
    public class AbsenceController : Controller
    {
        private readonly AppDbContext _context;

        public AbsenceController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(int pg = 1, string text = "")
        {

            if (HttpContext.Session.GetString("userAuthenticated") == "true")
            {
                List<Absence> absences;
                DateTime now = DateTime.Now;
                if (text != "" && text != null)
                {
                    absences = _context.Absences.Include(x => x.Employee).Where(p => p.Employee.fulleName.Contains(text)).ToList();

                }
                else
                {
                    absences = _context.Absences.Include(x => x.Employee).ToList();

                }
                foreach (var item in absences)
                {
                    if (item.Date_Fin < now.Date)
                    {
                        var x = _context.Employees.Find(item.EmployeeID);
                        x.statu = "WORKING";
                        _context.Employees.Update(x);
                        _context.SaveChanges();
                    }
                }
                const int pageSize = 6;
                if (pg < 1) pg = 1;
                int recsCount = absences.Count();
                var pager = new Pager(recsCount, pg, pageSize);
                this.ViewBag.Pager = pager;
                int recSkip = (pg - 1) * pageSize;
                var data = absences.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                ViewBag.Employees = _context.Employees.OrderBy(x => x.fulleName).ToList();
                return View(data);

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public IActionResult Create()
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                ViewBag.Employee = _context.Employees.OrderBy(x => x.fulleName).ToList();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Absence model)
        {

            UploadImage(model);
            if (ModelState.IsValid)
            {
                var data = _context.Employees.Find(model.EmployeeID);
                data.statu = "ABSENT";
                _context.Employees.Update(data);
                _context.Absences.Add(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public IActionResult Update(int? id)
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                var data = _context.Absences.Find(id);
                ViewBag.Employees = _context.Employees.OrderBy(x => x.fulleName).ToList();
                return View(data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Absence model)
        {
            UploadImage(model);
            if (ModelState.IsValid)
            {
                _context.Absences.Update(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Details(int? id)
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                var data = _context.Absences.Find(id);
                ViewBag.Employees = _context.Employees.Find(data.EmployeeID);
                return View(data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }



        public IActionResult Delete(int? id)
        {
            var hol = _context.Absences.Find(id);
            if (hol != null)
            {
                _context.Absences.Remove(hol);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));


        }
        private void UploadImage(Absence model)
        {
            var file = HttpContext.Request.Form.Files;
            var x = model.reason;
            if (file.Count() > 0)
            {
                string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(file[0].FileName);
                var fileStream = new FileStream(Path.Combine(@"wwwroot/", "Reasons", ImageName), FileMode.Create);
                file[0].CopyTo(fileStream);
                model.reason = ImageName;
                Console.Write(model.reason);
            }
            else if (model.reason == null && model.ID == null)
            {
                model.reason = "Default.png";
            }
            else
            {
                model.reason = x;
            }
        }
    }
}

Controllers/OperationController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Telintec_RH.Data;
using Telintec_RH.Models;

namespace Telintec_RH.Controllers
{
    public class OperationController : Controller
    {
        private readonly AppDbContext _context;

        public OperationController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(DateTime d1 = default(DateTime), DateTime d2 = default(DateTime), int pg = 1)
        {

            if (HttpContext.Session.GetString("userAuthenticated") == "true")
            {
                List<Operation> operations;
                if (d1!= default(DateTime) && d2!= default(DateTime))
                {
                    operations = _context.Operations.Include(x => x.Employee).Where(p => p.Date>= d1 && p.Date <= d2).ToList();

                }
                else
                {
                    operations = _context.Operations.Include(x => x.Employee).ToList();

                }
                const int pageSize = 6;
                if (pg < 1) pg = 1;
                int recsCount = operations.Count();
                var pager = new Pager(recsCount, pg, pageSize);
                this.ViewBag.Pager = pager;
                int recSkip = (pg - 1) * pageSize;
                var data = operations.Skip(recSkip).Take(pager.PageSize).ToList();
                this.ViewBag.Pager = pager;
                ViewBag.Employees = _context.Employees.OrderBy(x => x.fulleName).ToList();
                return View(data);

            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public IActionResult Create()
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                ViewBag.Employee = _context.Employees.OrderBy(x => x.fulleName).ToList();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Operation model)
        {

            UploadImage(model);
            if (ModelState.IsValid)
            {
                _context.Operations.Add(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Update(int? id)
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                var data = _context.Operations.Find(id);
                ViewBag.Employees = _context.Employees.OrderBy(x => x.fulleName).ToList();
                return View(data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Operation model)
        {
            UploadImage(model);
            if (ModelState.IsValid)
            {
                _context.Operations.Update(model);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Details(int? id)
        {
            if ((HttpContext.Session.GetString("userAuthenticated") == "true"))
            {
                var data = _context.Operations.Find(id);
                ViewBag.Employees = _context.Employees.Find(data.EmployeeID);
                return View(data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        public IActionResult Delete(int? id)
        {
            var hol = _context.Operations.Find(id);
            if (hol != null)
            {
                _context.Operations.Remove(hol);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));


        }

        private void UploadImage(Operation model)
        {
            var file = HttpContext.Request.Form.Files;
            var x = model.contrat;
            if (file.Count() > 0)
            {
                string ImageName = Guid.NewGuid().ToString() + Path.GetExtension(file[0].FileName);
                var fileStream = new FileStream(Path.Combine(@"wwwroot/", "Contracts", ImageName), FileMode.Create);
                file[0].CopyTo(fileStream);
                model.contrat = ImageName;
                Console.Write(model.contrat);
            }
            else if (model.contrat == null && model.ID == null)
            {
                model.contrat = "Default.png";
            }
            else
            {
                model.contrat = x;
            }
        }


    }
}

Views/Operation/Create.cshtml
@model Telintec_RH.Models.Operation

@{
    ViewData["Title"] = "Create-Operation";
}

<h1>Create</h1>

<h4>New Operation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" readonly/>
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contrat" class="control-label"></label>
                <input type="file" asp-for="contrat" class="form-control" />
                <span asp-validation-for="contrat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="montant" class="control-label"></label>
                <input asp-for="montant" class="form-control" />
                <span asp-validation-for="montant" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeID" class="control-label">Propriétaire</label>
                <select asp-for="EmployeeID" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Employee,"ID","fulleName" ))">
                    <option value="">Chose Employee...</option>
                </select>
                <span asp-validation-for="EmployeeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" style="background-color: #2A36B8 !important; color:white !important ; margin-top:10px !important; width:90px !important" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index" style="color:  #000C8E !important; text-decoration: none !important; font-size:16px !important; font-weight:600 !important; margin-top:10px !important;">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Operation/Details.cshtml
@model Telintec_RH.Models.Operation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Of Operation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.montant)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.montant)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.contrat)
        </dt>
        <dd class = "col-sm-10">
            <img src="~/Contracts/@Model.contrat" height="592px" width="492px" style="border-radius:15px !important;" />
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" style="color:  #000C8E !important; text-decoration: none !important; font-size:16px !important; font-weight:600 !important; margin-top:10px !important;">Back to List</a>
</div>

Views/Operation/Index.cshtml
@model IEnumerable<Telintec_RH.Models.Operation>

@{
    ViewData["Title"] = "Operations";
    int cmpt = 0;
    foreach (var item in Model)
    {
        cmpt += 1;
    }
    double income = 0;
    foreach (var item in Model)
    {
        income += item.montant;
    }
    Pager pager = new Pager();
    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<div style="display:flex; width:100%;">
    <div class="analytics">
        <div class="card">
            <h6>Total Operations</h6>
            <div class="card-head">
                <h4>@cmpt</h4>
            </div>
        </div>
    </div>
    <div class="analytics">
        <div class="card">
            <h6>Total Income</h6>
            <div class="card-head">
                <h4>@income</h4>
            </div>
            <h6>DH</h6>
        </div>
    </div>


</div>

<div style="display: flex !important; width:100%">
    <form asp-controller="Operation" asp-action="Index" style="width:70%">
        <input type="date" name="d1" placeholder="Search" style="color:gray ; width:30%; border-radius:7px;padding:7px; color:#000C8E " />
        <input type="date" name="d2" placeholder="Search" style="color:gray ; width:30%; border-radius:7px;padding:7px;  color:#000C8E " />
        <button type="submit" style="margin-left:5px; background-color:#000C8E; border-width:1px; border-color:#000C8E; padding:8px; border-radius:5px; height:40px; width:40px; margin-top:26px;">
            <i class="fa-solid fa-magnifying-glass" style="color:white"></i>
        </button>
    </form>
    <a style="text-decoration:none; background-color:#000C8E; color:white; border-width:1px; border-color:#000C8E;
       border-radius:7px; height:40px; width:9%; padding:8px; margin-left:285px; margin-top:29px" asp-action="Create">
        <i class="fa-solid fa-bars-progress" style="margin-right:5px"></i>
        <span>New</span>
    </a>
</div>
<div style="margin-top:30px; margin-bottom:0px; width:100%; height:35px; border-top-left-radius:9px;border-top-right-radius:9px;
     background-color:#000C8E; padding:6px">
    <p style="color:white; font-size:14px; font-weight:600; margin-left:20px">Operations Management</p>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.contrat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.montant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Employee.fulleName)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                    <img src="~/Contracts/@item.contrat" height="42px" width="42px" style="border-radius:15px !important;" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.montant)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Employee.fulleName)
            </td>
            <td>
                    <a asp-controller="Operation" asp-action="Update" asp-route-id="@item.ID" style="width: 32px;height: 32px; text-decoration:none; color:#2A36B8">
                        <i class="fa-regular fa-pen-to-square"></i>
                    </a> |
                    <a onclick="return confirm('Are you sure of deleting...?')" asp-controller="Operation" asp-action="Delete" asp-route-id="@item.ID" style="text-decoration:none;margin-left:5px;width: 32px;height: 32px;color:#2A36B8">
                        <i class="fa-solid fa-trash-can"></i>
                    </a> |
                    <a asp-controller="Operation" asp-action="Details" asp-route-id="@item.ID" style="width: 32px;height: 32px; text-decoration:none; color:#2A36B8">
                        <i class="fa-regular fa-eye"></i>
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>
<div class="pagination">
    @if (pager.TotalPages > 0)
    {
        <ul style="margin-top:45px !important">
            @if (pager.CurrentPage > 1)
            {
                <li style="display:inline">
                    <a class="prev-btn" asp-controller="Operation" asp-action="Index" asp-route-pg="@(pager.CurrentPage - 1)">&lt;before</a>
                </li>

            }
            @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
            {
                <li class="@(pge == pager.CurrentPage ? "active" : "page-item") " style="display:inline">
                    <a class="page-number" asp-controller="Absence" asp-action="Index" asp-route-pg="@pge">@pge</a>
                </li>
            }
            <li style="display:inline">
                <a asp-controller="Operation" asp-action="Index" asp-route-pg="@(pager.TotalPages)" class="prev-btn">next &gt; </a>
            </li>
        </ul>
    }

</div>

Views/Operation/Update.cshtml
@model Telintec_RH.Models.Operation

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>This Operation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label"></label>
                <input asp-for="ID" class="form-control" />
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="contrat" class="control-label"></label>
                <input type="file" asp-for="contrat" class="form-control" />
                <span asp-validation-for="contrat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="montant" class="control-label"></label>
                <input asp-for="montant" class="form-control" />
                <span asp-validation-for="montant" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmployeeID" class="control-label">Propriétaire</label>
                <select asp-for="EmployeeID" class="form-control"
                        asp-items="@(new SelectList(ViewBag.Employees,"ID","fulleName" ))">
                    <option value="">Chose Employee...</option>
                </select>
                <span asp-validation-for="EmployeeID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" style="background-color: #2A36B8 !important; color:white !important ; margin-top:10px !important; width:90px !important" />
            </div>
        </form>

    </div>
</div>

<div>
    <a asp-action="Index" style="color:  #000C8E !important; text-decoration: none !important; font-size:16px !important; font-weight:600 !important; margin-top:10px !important;">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}